server:
  port: 8060
  context-path: /admin
#  session:
#    timeout: 600
spring:
  jackson:
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql:///bookshop?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  http:
    multipart:
      max-file-size: 10MB
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    pool:
      max-wait: 10000
      max-idle: 20
      min-idle: 0
security:
  user:
    name: admin
    password: 123456